"""添加 user_profiles.nickname 字段

Revision ID: bd903b87f0da
Revises: 
Create Date: 2025-02-23 20:23:31.923619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd903b87f0da'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('nickname', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('bmi', sa.Float(), nullable=True))
    op.add_column('user_profiles', sa.Column('water_ratio', sa.Float(), nullable=True))
    op.add_column('user_profiles', sa.Column('eating_habits', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('diet_goal', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('short_term_goals', sa.JSON(), nullable=True))
    op.add_column('user_profiles', sa.Column('long_term_goals', sa.JSON(), nullable=True))
    op.add_column('user_profiles', sa.Column('goal_progress', sa.Float(), nullable=True))
    op.add_column('user_profiles', sa.Column('training_type', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('training_progress', sa.Float(), nullable=True))
    op.add_column('user_profiles', sa.Column('muscle_group_analysis', sa.JSON(), nullable=True))
    op.add_column('user_profiles', sa.Column('sleep_duration', sa.Float(), nullable=True))
    op.add_column('user_profiles', sa.Column('deep_sleep_percentage', sa.Float(), nullable=True))
    op.add_column('user_profiles', sa.Column('fatigue_score', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('recovery_activities', sa.JSON(), nullable=True))
    op.add_column('user_profiles', sa.Column('performance_metrics', sa.JSON(), nullable=True))
    op.add_column('user_profiles', sa.Column('exercise_history', sa.JSON(), nullable=True))
    op.add_column('user_profiles', sa.Column('training_time_preference', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('equipment_preferences', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'equipment_preferences')
    op.drop_column('user_profiles', 'training_time_preference')
    op.drop_column('user_profiles', 'exercise_history')
    op.drop_column('user_profiles', 'performance_metrics')
    op.drop_column('user_profiles', 'recovery_activities')
    op.drop_column('user_profiles', 'fatigue_score')
    op.drop_column('user_profiles', 'deep_sleep_percentage')
    op.drop_column('user_profiles', 'sleep_duration')
    op.drop_column('user_profiles', 'muscle_group_analysis')
    op.drop_column('user_profiles', 'training_progress')
    op.drop_column('user_profiles', 'training_type')
    op.drop_column('user_profiles', 'goal_progress')
    op.drop_column('user_profiles', 'long_term_goals')
    op.drop_column('user_profiles', 'short_term_goals')
    op.drop_column('user_profiles', 'diet_goal')
    op.drop_column('user_profiles', 'eating_habits')
    op.drop_column('user_profiles', 'water_ratio')
    op.drop_column('user_profiles', 'bmi')
    op.drop_column('user_profiles', 'age')
    op.drop_column('user_profiles', 'nickname')
    # ### end Alembic commands ###
